spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics, resilience4j.circuitbreakers
  metrics:
    export:
      prometheus:
        enabled: true

  resilience4j:
    circuitbreaker:
      instances:
        paymentGateway:
          sliding-window-size: 10
          failure-rate-threshold: 50
          wait-duration-in-open-state: 10000ms
          permitted-number-of-calls-in-half-open-state: 3
          register-health-indicator: true
    retry:
      instances:
        paymentGateway:
          max-attempts: 3
          wait-duration: 500ms
          enable-exponential-backoff: true
          exponential-backoff-multiplier: 2