spring:
  config:
    activate:
      on-profile: dev

  # Banco de Dados de Desenvolvimento (H2 em memória)
  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # Conexão com os containers NoSQL/Cache/Kafka locais
  data:
    mongodb:
      uri: mongodb://localhost:27017/payment_audit
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8081

logging:
  level:
    com.example.payment: DEBUG
    org.hibernate.SQL: DEBUG